-- MySQL Script generated by MySQL Workbench
-- jeu. 27 janv. 2022 16:37:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projet_njs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projet_njs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projet_njs` DEFAULT CHARACTER SET utf8 ;
USE `projet_njs` ;

-- -----------------------------------------------------
-- Table `projet_njs`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_njs`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prenom` VARCHAR(50) NOT NULL,
  `nom` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `avatar_path` VARCHAR(5000) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projet_njs`.`commentaires`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_njs`.`commentaires` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `content` VARCHAR(5000) NOT NULL,
  `date` DATETIME NOT NULL DEFAULT current_timestamp,
  `id_com_parent` INT NULL,
  `id_articles` INT NULL,
  INDEX `fk_com_list_1_idx` (`id_user` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_com_list_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `projet_njs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projet_njs`.`creations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_njs`.`creations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` LONGTEXT NOT NULL,
  `date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `isDelete` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projet_njs`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_njs`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `img_url` VARCHAR(5000) NOT NULL,
  `id_creations` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_images_1_idx` (`id_creations` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_images_1`
    FOREIGN KEY (`id_creations`)
    REFERENCES `projet_njs`.`creations` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `projet_njs`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_njs`.`role` (
  `id_user` INT NOT NULL,
  `isBan` TINYINT NOT NULL,
  `isArchive` TINYINT NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  CONSTRAINT `fk_role_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `projet_njs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_njs`.`avis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_njs`.`avis` (
  `id_user` INT NOT NULL,
  `content` VARCHAR(5000) NOT NULL,
  `note` INT NOT NULL,
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  CONSTRAINT `fk_avis_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `projet_njs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_njs`.`com_list_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_njs`.`com_list_likes` (
  `id_com` INT NOT NULL,
  `id_user` INT NOT NULL,
  `liked` TINYINT NOT NULL,
  INDEX `fk_com_list_likes_1_idx` (`id_user` ASC) VISIBLE,
  INDEX `fk_com_list_likes_2_idx` (`id_com` ASC) VISIBLE,
  CONSTRAINT `fk_com_list_likes_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `projet_njs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_com_list_likes_2`
    FOREIGN KEY (`id_com`)
    REFERENCES `projet_njs`.`commentaires` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projet_njs`.`users_creations_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projet_njs`.`users_creations_likes` (
  `id_user` INT NOT NULL,
  `id_creations` INT NOT NULL,
  `liked` TINYINT NOT NULL,
  INDEX `fk_user_creations_likes_2_idx` (`id_creations` ASC) VISIBLE,
  INDEX `fk_user_creations_likes_1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_creations_likes_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `projet_njs`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_creations_likes_2`
    FOREIGN KEY (`id_creations`)
    REFERENCES `projet_njs`.`creations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO users (prenom, nom, email, password, avatar_path)
  VALUES
   ('axel', 'etoile', 'axel@fr.fre', '1234', '/fezrsf'),
   ('axel1', 'etoile2', 'axel1@fr.fre', '1234', '/fezrsf'),
   ('axel2', 'etoile1', 'axel2@fr.fre', '1234', '/fezrsf')
;

INSERT INTO creations (description, isDelete)
  VALUES
   ('Ma super descr 1', "0")
;

INSERT INTO images (img_url, id_creations)
  VALUES
   ('1641736475301_1_a.jpg', "1"),
   ('1641752074122_2b.jpg', "1")
;

INSERT INTO role (id_user, isBan, isArchive, isAdmin)
  VALUES
   ('1', '0', '0', '1'),
   ('2', '0', '0', '0'),
   ('3', '0', '0', '0')
;